# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Tushar's blog"
email: ""
description: > # this means to ignore newlines until "baseurl:"
  A Technical blog(by Tushar Chauhan)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tushar-chauhan.github.io" # the base hostname & protocol for your site
twitter_username: chauhan_tushar
github_username:  tushar-chauhan
paginate: 5
repository: tushar-chauhan/tushar-chauhan.github.io
author:
  github: tushar-chauhan

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Plugins
plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
